name: Sample Composite Action

inputs:
  multiplier:
    description: 'Multiplier'
    required: true
    default: 1
outputs:
  product-number:
    description: "Product number"
    value: ${{ steps.generator.outputs.product-number }}

runs:
  using: "composite"
  steps:
    - name: Generator
      id: generator
      run: |
        random_number=$RANDOM
        multiplier=${{ inputs.multiplier }}
        echo "random_number=$random_number"
        echo "multiplier=$multiplier"
        echo "product-number=$(echo $(( $random_number*$multiplier )))" >> $GITHUB_OUTPUT
      shell: bash
