name: Build and Test (Npm)
description: Run build and test on npm package
inputs:
  version:
    description: Semantic version to be set as npm package version, skip if unset
  pack:
    description: Whether to pack a package in zip file
    default: 'false'
outputs:
  package-name:
    description: Npm package name
    value: ${{ steps.pack-contents.outputs.package-name }}
  content-filename:
    description: Content filename
    value: ${{ steps.pack-contents.outputs.content-filename }}

runs:
  using: composite
  steps:
    - name: Set Package Version
      run: |
        [[ "${{ inputs.version }}" ]] && npm pkg set version="${{ inputs.version }}"
      shell: bash
    - name: Clean Install
      run: npm ci
      shell: bash
    - name: Build Package
      run: npm run build
      shell: bash
    - name: Test Package
      run: npm test
      shell: bash
    - name: Pack Contents
      id: pack-contents
      run: |
        PACKAGE_NAME=$(npm pkg get name)
        if [[ "$PACKAGE_NAME" == "{}" ]]; \
          then PACKAGE_NAME=; \
          else PACKAGE_NAME=${PACKAGE_NAME//\"/}; \
        fi
        [[ "${{ inputs.pack }}" == [Tt][Rr][Uu][Ee] ]] && CONTENT_FILENAME=$(npm pack)
        echo "package-name=$PACKAGE_NAME" >> $GITHUB_OUTPUT
        echo "content-filename=$CONTENT_FILENAME" >> $GITHUB_OUTPUT
      shell: bash
