name: Publish Prerelease

on:
  workflow_dispatch:

jobs:
  publish-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      # bump version as prerelease
      - uses: ./.github/actions/bump-semantic-version
        id: bump-prerelease-version
        with:
          type: patch
          prerelease: true
          prerelease-id: rc
          tag-prefix: release/
      # push git tag and create GitHub prerelease
      - uses: ./.github/actions/create-github-release
        id: create-prerelease-release
        with:
          tag-name: release/${{ steps.bump-prerelease-version.outputs.version }}
          prerelease: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
