name: Publish Release as Prerelease

on:
  workflow_dispatch:

jobs:
  publish-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      # bump version as prerelease
      - uses: ./.github/actions/bump-semantic-version
        id: bump-prerelease-version
        with:
          type: patch
          prerelease: true
          prerelease-id: rc
          tag-prefix: release/
      # push git tag
      - run: |
          echo version=$VERSION
          git tag release/$VERSION
          git push --tags
        env:
          VERSION: ${{ steps.bump-prerelease-version.outputs.version }}
