name: Publish Release

on:
  workflow_dispatch:
    inputs:
      release-type:
        description: Release Type
        required: true
        default: patch
        type: choice
        options:
          - major
          - minor
          - patch

jobs:
  publish-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      # bump semantic version as release
      - uses: ./.github/actions/bump-semantic-version
        id: bump-release-version
        with:
          type: patch
          tag-prefix: release/
      # push git tag and create GitHub release
      - uses: ./.github/actions/create-github-release
        id: create-release-release
        with:
          tag-name: release/${{ steps.bump-release-version.outputs.version }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
