name: Publish Prerelease

on:
  workflow_call:
    inputs:
      release-type:
        description: Release Type
        type: string
        required: true
        default: patch

jobs:
  publish-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-tags: true
      # bump semantic version as prerelease
      - uses: ./.github/actions/bump-semantic-version
        id: bump-prerelease-version
        with:
          type: ${{ inputs.release-type }} 
          prerelease: true
          tag-prefix: release/
      # push git tag and create GitHub prerelease
      - uses: ./.github/actions/create-github-release
        id: create-prerelease-release
        with:
          tag-name: release/${{ steps.bump-prerelease-version.outputs.version }}
          prerelease: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
