name: Publish Release

on:
  workflow_call:
    inputs:
      release-type:
        description: Release type for version resolution
        type: string
        required: true
        default: patch
      tag-prefix:
        description: Tag prefix for identifying version
        type: string
        default: ${{ vars.STARTER_KIT_TAG_PREFIX }}
    secrets:
      STARTER_KIT_ACTIONS_TOKEN:
        description: A personal access token (PAT) for used in GitHub Actions
        required: true

jobs:
  publish-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-tags: true
      # bump semantic version as release
      - uses: kimichiro/starter-kit-github-actions/.github/actions/bump-semantic-version@HEAD
        id: bump-release-version
        with:
          type: ${{ inputs.release-type }} 
          tag-prefix: ${{ inputs.tag-prefix }}
      # push git tag and create GitHub release
      - uses: kimichiro/starter-kit-github-actions/.github/actions/create-github-release@HEAD
        id: create-release-release
        with:
          tag-name: ${{ inputs.tag-prefix }}${{ steps.bump-release-version.outputs.version }}
        env:
          GITHUB_TOKEN: ${{ secrets.STARTER_KIT_ACTIONS_TOKEN }}
