# This is a basic workflow that is manually triggered through GitHub site or REST API
name: Sample Manual Workflow

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Person to greet'
        default: 'GitHub'
        required: true
        type: string
      reusable-greet:
        description: Trigger reusable greet
        default: false
        type: boolean

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
      - name: Send greeting
        run: echo "Hello ${{ inputs.name }}"
      - name: Conditional greeting with reusable action
        if: ${{ inputs.reusable-greet }}
        uses: actions/hello-world-javascript-action@main
        with:
          who-to-greet: "[[${{ inputs.name }}]]"
  call-absolute-private-workflow:
    uses: kimichiro/starter-kit-github/.github/workflows/sample-callable.yml@main
  call-relative-private-workflow:
    uses: ./.github/workflows/sample-callable.yml
