# This is a callable workflow that is reusable to other workflow
name: Sample Callable Workflow

on:
  workflow_call:
    inputs:
      caller:
        required: true
        type: string
    secrets:
      sample-secret:
        required: true
    outputs:
      file_count:
        description: "Git files count"
        value: ${{ jobs.list-git-files.outputs.file_count }}
  workflow_dispatch:

jobs:
  print-variables:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: |
          echo "vars.sample_variable_string=[${{ vars.sample_variable_string }}]"
          echo "vars.sample_variable_boolean=[${{ vars.sample_variable_boolean }}]"
          echo "vars.sample_variable_number=[${{ vars.sample_variable_number }}]"
          echo "vars.sample_variable_json=[${{ vars.sample_variable_json }}]"
      - run: node -p "console.log('${{ vars.sample_variable_json }}')"
      - run: |
          echo "inputs.caller=[${{ inputs.caller }}]"
          echo "inputs.secrets=[${{ inputs.secrets }}]"
  list-git-files:
    runs-on: ubuntu-latest
    outputs:
      file_count: ${{ steps.count-git-file.outputs }}
    steps:
      - uses: actions/checkout@v4
      - name: List trackable files
        run: git ls-tree -r main --name-only
      - name: Count trackable files
        id: count-git-file
        run: git ls-files | wc -l >> $GITHUB_OUTPUT
