# This is a basic workflow that is manually triggered through GitHub site or REST API
name: Sample Manual Workflow

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Person to greet'
        default: 'GitHub'
        required: true
        type: string
      reusable-greet:
        description: Trigger reusable greet
        default: false
        type: boolean

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
      - name: Send greeting
        run: echo "Hello ${{ inputs.name }}"
      - name: Conditional greeting with reusable action
        if: ${{ inputs.reusable-greet }}
        uses: actions/hello-world-javascript-action@main
        with:
          who-to-greet: "[[${{ inputs.name }}]]"
  call-absolute-private-workflow:
    uses: kimichiro/starter-kit-github-actions/.github/workflows/sample-callable.yml@main
    with:
      caller: call-absolute-private-workflow
    secrets: inherit
  call-relative-private-workflow:
    uses: ./.github/workflows/sample-callable.yml
    with:
      caller: call-relative-private-workflow
    secrets:
      sample_secret: a sadly visible secret
  call-relative-private-composite-action:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: ls -Ralt
      - uses: ./.github/actions/sample-composite-action.yml
        id: sample-composite-action
        with:
          multiplier: 4
      - run: echo "product-number=[${{ steps.sample-composite-action.outputs.product-number }}]"
  needs-callables:
    needs: [call-absolute-private-workflow, call-relative-private-workflow]
    runs-on: ubuntu-latest
    steps:
      - name: Print results from callables
        env:
          file_count_1: ${{ needs.call-absolute-private-workflow.outputs.file_count }}
          file_count_2: ${{ needs.call-relative-private-workflow.outputs.file_count }}
        run: |
          echo "[call-absolute-private-workflow] output->file_count: ${{ env.file_count_1 }}"
          echo "[call-relative-private-workflow] output->file_count: ${{ env.file_count_2 }}"
