name: Sample Publish Prerelease

on:
  workflow_dispatch:
    inputs:
      release-type:
        description: Release Type
        required: true
        default: patch
        type: choice
        options:
          - major
          - minor
          - patch

jobs:
  publish-release:
    permissions:
      contents: write
    uses: ./.github/workflows/publish-prerelease.yml
    with:
      release-type: ${{ inputs.release-type }}
    secrets: inherit
