# This is a callable workflow that is reusable to other workflow
name: Sample Callable Workflow

on:
  workflow_call:
  workflow_dispatch:

jobs:
  print-variables:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: |
          echo "vars.sample_variable_string=[${{ vars.sample_variable_string }}]"
          echo "vars.sample_variable_boolean=[${{ vars.sample_variable_boolean }}]"
          echo "vars.sample_variable_number=[${{ vars.sample_variable_number }}]"
          echo "vars.sample_variable_json=[${{ vars.sample_variable_json }}]"
      - run: node -p "console.log('${{ vars.sample_variable_json }}')"
  list-git-files:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: List trackable files
        run: git ls-tree -r main --name-only
